<?php
declare(strict_types=1);
require __DIR__.'/../api/config.php'; requireAdmin();
$pdo=db(); $q=trim((string)($_GET['q']??'')); $dep=trim((string)($_GET['departamento']??'')); $from=(string)($_GET['desde']??''); $to=(string)($_GET['hasta']??'');
$where=[];$params=[];
if($q!==''){$where[]='(nombre LIKE ? OR correo LIKE ? OR municipio LIKE ?)';$term='%'.$q.'%';array_push($params,$term,$term,$term);}
if($dep!==''){$where[]='departamento=?';$params[]=$dep;} if($from!==''){$where[]='DATE(creado_en)>=?';$params[]=$from;} if($to!==''){$where[]='DATE(creado_en)<=?';$params[]=$to;}
$whereSql=$where?' WHERE '.implode(' AND ',$where):'';
if(isset($_GET['exportar'])){
  $stmt=$pdo->prepare('SELECT id,nombre,correo,departamento,municipio,calificacion,comentario,estado,creado_en FROM test_historial'.$whereSql.' ORDER BY creado_en DESC');$stmt->execute($params);
  header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="historial-test-'.date('Y-m-d').'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,['ID','Nombre','Correo','Departamento','Municipio','Calificación','Comentario','Estado','Fecha']);while($row=$stmt->fetch())fputcsv($out,$row);fclose($out);exit;
}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['eliminar'])){$id=(int)$_POST['eliminar'];$stmt=$pdo->prepare('DELETE FROM test_historial WHERE id=?');$stmt->execute([$id]);header('Location: index.php?eliminado=1');exit;}
$page=max(1,(int)($_GET['pagina']??1));$perPage=20;$count=$pdo->prepare('SELECT COUNT(*) FROM test_historial'.$whereSql);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);
$stmt=$pdo->prepare('SELECT * FROM test_historial'.$whereSql.' ORDER BY creado_en DESC LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$stmt->execute($params);$rows=$stmt->fetchAll();
$departments=$pdo->query('SELECT DISTINCT departamento FROM test_historial ORDER BY departamento')->fetchAll(PDO::FETCH_COLUMN);
$stats=$pdo->query('SELECT COUNT(*) total,COUNT(DISTINCT correo) participantes,ROUND(AVG(calificacion),1) promedio FROM test_historial')->fetch();
function decoded($json){return json_decode((string)$json,true)?:[];} function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Historial del test</title><link rel="stylesheet" href="admin.css"></head><body>
<header class="admin-header"><div><h1>Historial del test vocacional</h1><p>Becas por Nuestro Futuro</p></div><nav><a href="../testvocacional.html">Abrir test</a><a href="logout.php">Cerrar sesión</a></nav></header>
<main class="admin-main"><section class="stats"><article><span>Registros</span><strong><?=h($stats['total'])?></strong></article><article><span>Correos únicos</span><strong><?=h($stats['participantes'])?></strong></article><article><span>Calificación promedio</span><strong><?=h($stats['promedio']??0)?> / 5</strong></article></section>
<?php if(isset($_GET['eliminado'])):?><div class="message success">Registro eliminado correctamente.</div><?php endif;?>
<form class="filters" method="get"><input name="q" value="<?=h($q)?>" placeholder="Nombre, correo o municipio"><select name="departamento"><option value="">Todos los departamentos</option><?php foreach($departments as $d):?><option <?=($dep===$d?'selected':'')?>><?=h($d)?></option><?php endforeach;?></select><input type="date" name="desde" value="<?=h($from)?>"><input type="date" name="hasta" value="<?=h($to)?>"><button>Filtrar</button><a href="index.php">Limpiar</a><button name="exportar" value="1">Exportar CSV</button></form>
<div class="table-wrap"><table><thead><tr><th>ID</th><th>Fecha</th><th>Participante</th><th>Ubicación</th><th>Calificación</th><th>Resultado</th><th>Acciones</th></tr></thead><tbody>
<?php if(!$rows):?><tr><td colspan="7" class="empty">No hay registros con estos filtros.</td></tr><?php endif;?>
<?php foreach($rows as $row):$aff=decoded($row['afinidades']);arsort($aff);$answers=decoded($row['respuestas']);$careers=decoded($row['carreras_recomendadas']);$centers=decoded($row['centros_mostrados']);?><tr><td>#<?=h($row['id'])?></td><td><?=h(date('d/m/Y H:i',strtotime($row['creado_en'])))?></td><td><strong><?=h($row['nombre'])?></strong><small><?=h($row['correo'])?></small></td><td><?=h($row['municipio'])?><small><?=h($row['departamento'])?></small></td><td><?=str_repeat('★',(int)$row['calificacion'])?><?=str_repeat('☆',5-(int)$row['calificacion'])?></td><td><details><summary>Ver detalle</summary><div class="detail"><h3>Afinidades</h3><p><?php foreach($aff as $area=>$pct):?><span class="chip"><?=h($area)?>: <?=h($pct)?>%</span><?php endforeach;?></p><h3>Respuestas</h3><ol><?php foreach($answers as $a):?><li><?=h($a['pregunta']??'')?> <strong><?=h($a['respuesta']??'')?></strong></li><?php endforeach;?></ol><h3>Carreras recomendadas</h3><pre><?=h(json_encode($careers,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre><h3>Centros mostrados (<?=count($centers)?>)</h3><ul><?php foreach($centers as $c):?><li><?=h($c['nombre']??'')?></li><?php endforeach;?></ul><?php if($row['comentario']):?><h3>Comentario</h3><p><?=nl2br(h($row['comentario']))?></p><?php endif;?></div></details></td><td><form method="post" onsubmit="return confirm('¿Eliminar este registro definitivamente?')"><button class="danger" name="eliminar" value="<?=h($row['id'])?>">Eliminar</button></form></td></tr><?php endforeach;?></tbody></table></div>
<nav class="pagination"><?php for($i=1;$i<=$pages;$i++):?><a class="<?=$i===$page?'active':''?>" href="?<?=h(http_build_query(array_merge($_GET,['pagina'=>$i])))?>"><?=$i?></a><?php endfor;?></nav></main></body></html>
